# Generated by Django 5.1 on 2026-05-18 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motos', '0007_cargomoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='motos/galeria/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='motos.modelomoto')),
            ],
            options={
                'verbose_name': 'Foto de Modelo',
                'verbose_name_plural': 'Fotos de Modelo',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
