# Generated by Django 5.2.14 on 2026-05-16 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('motos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('dias', models.PositiveIntegerField()),
                ('monto_total_usd', models.DecimalField(decimal_places=2, max_digits=8)),
                ('metodo_pago', models.CharField(choices=[('bitcoin_btcpay', 'Bitcoin (BTCPay)'), ('cash', 'Efectivo')], max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('payment_id', models.CharField(blank=True, max_length=200)),
                ('contrato_pdf', models.FileField(blank=True, upload_to='contratos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Órdenes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.TextField()),
            ],
            options={
                'verbose_name': 'Respuesta de Cliente',
                'verbose_name_plural': 'Respuestas de Cliente',
            },
        ),
        migrations.CreateModel(
            name='LineaOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_dia', models.DecimalField(decimal_places=2, max_digits=8)),
                ('subtotal_usd', models.DecimalField(decimal_places=2, max_digits=8)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='motos.modelomoto')),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='motos.moto')),
            ],
            options={
                'verbose_name': 'Línea de Orden',
                'verbose_name_plural': 'Líneas de Orden',
            },
        ),
    ]
