# Generated by Django 5.2.14 on 2026-05-16 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formularios', '0001_initial'),
        ('reservas', '0001_initial'),
        ('tiendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='tiendas.tienda'),
        ),
        migrations.AddField(
            model_name='lineaorden',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='reservas.orden'),
        ),
        migrations.AddField(
            model_name='respuestacliente',
            name='campo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='formularios.campoformulario'),
        ),
        migrations.AddField(
            model_name='respuestacliente',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='reservas.orden'),
        ),
    ]
