# Generated by Django 5.1 on 2026-05-31 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='operation',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operaciones', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='operation',
            name='cuenta_contraparte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.account'),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('tienda', 'nombre')},
        ),
    ]
