# Generated by Django 5.2.14 on 2026-05-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampoFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Campo de Formulario',
                'verbose_name_plural': 'Campos de Formulario',
            },
        ),
        migrations.CreateModel(
            name='PlantillaContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Plantilla de Contrato',
                'verbose_name_plural': 'Plantillas de Contrato',
            },
        ),
    ]
