# Generated by Django 5.1 on 2026-05-31 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('whatsapp_activo', models.BooleanField(default=True)),
                ('whatsapp_numero', models.CharField(blank=True, max_length=20)),
                ('btcpay_activo', models.BooleanField(default=False)),
                ('btcpay_url', models.CharField(blank=True, max_length=500)),
                ('btcpay_api_key', models.CharField(blank=True, max_length=500)),
                ('btcpay_store_id', models.CharField(blank=True, max_length=200)),
                ('btcpay_webhook_secret', models.CharField(blank=True, max_length=500)),
                ('logo', models.ImageField(blank=True, upload_to='logos/')),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Shop',
                'verbose_name_plural': 'Shops',
            },
        ),
    ]
