# Generated by Django 5.1 on 2026-05-31 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='dueno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tiendas', to=settings.AUTH_USER_MODEL),
        ),
    ]
