# Generated by Django 5.1 on 2026-05-31 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, upload_to='motos/')),
                ('caracteristicas', models.JSONField(blank=True, default=list)),
                ('min_dias_alquiler', models.PositiveIntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos', to='shops.shop')),
            ],
            options={
                'verbose_name': 'Unit Model',
                'verbose_name_plural': 'Unit Models',
                'ordering': ['marca', 'modelo'],
            },
        ),
        migrations.CreateModel(
            name='UnitCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='units.unitmodel')),
            ],
            options={
                'verbose_name': 'Unit Charge',
                'verbose_name_plural': 'Unit Charges',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('chapa', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motos', to='shops.shop')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='motos', to='units.unitmodel')),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
            },
        ),
        migrations.CreateModel(
            name='PricePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_min', models.PositiveIntegerField(default=1)),
                ('dias_max', models.PositiveIntegerField(blank=True, null=True)),
                ('precio_dia', models.DecimalField(decimal_places=2, max_digits=8)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='units.unitmodel')),
            ],
            options={
                'verbose_name': 'Price Plan',
                'verbose_name_plural': 'Price Plans',
                'ordering': ['dias_min'],
            },
        ),
        migrations.CreateModel(
            name='UnitPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='motos/galeria/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='units.unitmodel')),
            ],
            options={
                'verbose_name': 'Unit Photo',
                'verbose_name_plural': 'Unit Photos',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
