# Generated by Django 5.2.14 on 2026-05-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('whatsapp_numero', models.CharField(blank=True, max_length=20)),
                ('btcpay_url', models.CharField(blank=True, max_length=500)),
                ('btcpay_api_key', models.CharField(blank=True, max_length=500)),
                ('btcpay_store_id', models.CharField(blank=True, max_length=200)),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tienda',
                'verbose_name_plural': 'Tiendas',
            },
        ),
    ]
