# Generated by Django 5.1 on 2026-05-31 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forms', '0001_initial'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracttemplate',
            name='tienda',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plantillacontrato', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='formfield',
            name='tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='shops.shop'),
        ),
        migrations.AlterUniqueTogether(
            name='formfield',
            unique_together={('tienda', 'variable')},
        ),
    ]
