# Generated by Django 5.1 on 2026-05-31 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerresponse',
            name='campo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms.formfield'),
        ),
    ]
