# Generated by Django 5.1 on 2026-05-31 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_initial'),
        ('shops', '0001_initial'),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='customerresponse',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='bookings.order'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='units.unitmodel'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='moto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='units.unit'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='bookings.order'),
        ),
    ]
